# Taskfile for NixOS RPi5 Kiosk System
# Common tasks for building, deploying, and managing secrets

version: "3"

tasks:
  build-image:
    desc: Build SD card image for Raspberry Pi 5
    cmds:
      - nix build .#nixosConfigurations.rpi-kiosk.config.system.build.images.sd-card
    vars:
      image_path:
        sh: echo result/sd-image-aarch64-linux.img

  encrypt-secrets:
    desc: Encrypt secrets using SOPS
    cmds:
      - sops -e secrets/wifi.yaml > secrets/wifi.age

  decrypt-secrets:
    desc: Decrypt secrets using SOPS
    cmds:
      - sops -d secrets/wifi.age > secrets/wifi.yaml

  validate:
    desc: Validate flake and run checks
    cmds:
      - nix flake check
